version: '3.9'

services:
  backend:
    build: .

    container_name: backend-server

    ports:
      - '5000:5000'

    env_file:
      - .env.development

    environment:
      NODE_ENV: development

    depends_on:
      - mongo
      - redis

    restart: always

  mongo:
    image: mongo:7

    container_name: mongodb

    ports:
      - '27017:27017'

    volumes:
      - mongo-data:/data/db

    restart: always

  redis:
    image: redis:7-alpine

    container_name: redis-server

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    restart: always

volumes:
  mongo-data:
  redis-data:
